module

public import GinibrePoincare.Analysis.GinibreStochasticPuncturedUnitFieldGlobalIntegral
public import GinibrePoincare.Analysis.BrownianIntegralGaussianPuncturedShiftedLimit
public import GinibrePoincare.Analysis.BrownianIntegralGaussianBrownian

@[expose] public section

/-! Genuine Brownian motion generated by an actual adapted continuous unit
field. Its innovations are independent of the original full completed past. -/
open Set MeasureTheory ProbabilityTheory Filter
open scoped Topology NNReal
namespace GinibrePoincare
noncomputable section
set_option maxHeartbeats 1500000

theorem ginibrePuncturedUnitField_Brownian_exists
    {Ω ι : Type*} [MeasurableSpace Ω] [Fintype ι] [DecidableEq ι]
    (B : ι → ℝ≥0 → Ω → ℝ) (P : Measure Ω) [IsProbabilityMeasure P] [P.IsComplete]
    (hB : ∀ i, IsBrownianReal (B i) P)
    (hind : iIndepFun (fun i ω t => B i t ω) P)
    (u : ℝ≥0 → Ω → EuclideanSpace ℝ ι)
    (hu : ∀ t, @Measurable Ω (EuclideanSpace ℝ ι)
      (ginibreBrownianAugmentedFiltration B P (fun i => (hB i).toIsPreBrownianReal) t) _ (u t))
    (hunit : ∀ t ω, ‖u t ω‖=1)
    (hc : ∀ᵐ ω ∂P, ContinuousOn (fun t => u t ω) (Ioi 0)) (i₀ : ι) :
    ∃ β : ℝ≥0 → Ω → ℝ,
      IsBrownianReal β P ∧
      Martingale β (ginibreBrownianAugmentedFiltration B P (fun i => (hB i).toIsPreBrownianReal)) P ∧
      (∀ t, MemLp (β t) 2 P) ∧ β 0 =ᵐ[P] (fun _ => 0) ∧
      (∀ t, TendstoInMeasure P (fun k ω =>
        ∑ i, brownianUniformLeftSum (B i) (fun s ω => u s ω i) t (k+1) ω) atTop (β t)) ∧
      (∀ s t, TendstoInMeasure P (fun k => brownianUnitShiftedUniformSum B u s t (k+1))
        atTop (fun ω => β (s+t) ω-β s ω)) ∧
      (∀ s t (Y : Ω → ℝ),
        @Measurable Ω ℝ (ginibreBrownianAugmentedFiltration B P (fun i => (hB i).toIsPreBrownianReal) s) _ Y →
        IndepFun Y (fun ω => β (s+t) ω-β s ω) P) := by
  classical
  let F := ginibreBrownianAugmentedFiltration B P (fun i => (hB i).toIsPreBrownianReal)
  obtain ⟨β,hβ,hβC,hβL,hβ0,hβS,hβLaw⟩ :=
    ginibrePuncturedUnitField_global_continuous_integral_exists B P hB hind u hu hunit hc i₀
  have hbnd (t : ℝ≥0) (ω : Ω) (i : ι) : ‖u t ω i‖ ≤ 1 := by
    simpa only [hunit t ω] using PiLp.norm_apply_le (u t ω) i
  have hui (t : ℝ≥0) (i : ι) : MemLp (fun ω => u t ω i) 2 P := MemLp.of_bound
    (((PiLp.continuous_apply 2 (fun _ : ι => ℝ) i).measurable.comp (hu t)).mono
      (F.le t) le_rfl).aestronglyMeasurable 1 (Eventually.of_forall (fun ω => hbnd t ω i))
  have hshift (s t : ℝ≥0) := brownianUnitShiftedUniformSum_punctured_tendstoInMeasure_of_horizon_limits
    B P (fun i => (hB i).toIsPreBrownianReal) hind u hu hui hc 1 (by norm_num) hbnd
    s t (β (s+t)) (β s) (hβS (s+t)) (hβS s)
  have hBrown := brownianUnitField_actual_integral_isBrownian B P
    (fun i => (hB i).toIsPreBrownianReal) hind u hu hunit i₀ β hβ.1 hβ0 hβC hshift
  refine ⟨β,hBrown,hβ,hβL,hβ0,hβS,hshift,?_⟩
  intro s t Y hY
  exact (brownianUnitShiftedUniformSum_limit_gaussian_independent B P
    (fun i => (hB i).toIsPreBrownianReal) hind u hu hunit i₀ s t _ (hshift s t) Y hY).2
#print axioms ginibrePuncturedUnitField_Brownian_exists
end
end GinibrePoincare
