module

public import GinibrePoincare.Analysis.MultivariateComplexHermite
public import GinibrePoincare.Analysis.GeneralizedLaguerre
public import GinibrePoincare.Analysis.PairwiseRadius
public import GinibrePoincare.Analysis.CenterOfMassEigenfunctions

@[expose] public section

/-!
# Concrete Hermite–Laguerre polynomials (Theorem 1.4 infrastructure)

The family below uses the paper's normalized complex Hermite polynomials
and classical generalized Laguerre polynomials. The full concrete generator
identity is proved in `PolynomialEigenfunctionGenerator.lean` and equilibrium
orthogonality in `PolynomialEquilibriumOrthogonality.lean`. The algebraic basis
and unique finite expansions are proved in `PolynomialEigenfunctionBasis.lean`.
-/

open scoped BigOperators ComplexConjugate
namespace GinibrePoincare
noncomputable section

/-- The sum coordinate `S`. -/
def S_observable {n : ℕ} : Configuration n → ℂ := coordinateSum

/-- The pair-distance radius `R`. -/
def R_poly {n : ℕ} : Configuration n → ℝ := pairwiseRadius

theorem R_poly_eq (n : ℕ) (z : Configuration n) :
    R_poly z = n * ∑ j : Fin n, Complex.normSq (z j - S_observable z / (n : ℂ)) := by
  simpa [R_poly, radialObservable, recenteredSqNorm, configurationNormSq,
    recenteredConfiguration, projectToOrthogonal, projectToCenterLine, S_observable] using pairwiseRadius_eq_radialObservable z

/-- Membership in the actual polynomial algebra generated by `S`, `conj S`, `R`. -/
def IsPolynomialInSConjSR {n : ℕ} (f : Configuration n → ℂ) : Prop :=
  ∃ Q : MvPolynomial (Fin 3) ℂ,
    ∀ z, f z = MvPolynomial.eval ![S_observable z, conj (S_observable z), (R_poly z : ℂ)] Q

/-- Eigenvalue at an arbitrary paper speed `α`. -/
def eigenvalueAtSpeed (n : ℕ) (α : ℝ) (a b m : ℕ) : ℝ :=
  2 * (α / (n : ℝ)) * ((a : ℝ) + b + 2 * m)

/-- Eigenvalue for the concrete pregenerator, whose speed is `α_n=n`. -/
def eigenvalue (_n : ℕ) (a b m : ℕ) : ℝ :=
  2 * ((a : ℝ) + b + 2 * m)

theorem eigenvalueAtSpeed_concrete (n a b m : ℕ) (hn : 0 < n) :
    eigenvalueAtSpeed n n a b m = eigenvalue n a b m := by
  simp [eigenvalueAtSpeed, eigenvalue, ne_of_gt (show (0 : ℝ) < n by exact_mod_cast hn)]

structure PolynomialEigenfunctionData (n : ℕ) where
  a : ℕ
  b : ℕ
  m : ℕ

/-- The paper's actual Hermite–Laguerre polynomial `H_ab(S) L_m^(κ-1)(R)`. -/
def polynomialEigenfunction (n : ℕ) (ped : PolynomialEigenfunctionData n)
    (z : Configuration n) : ℂ :=
  ComplexHermite.normalizedEval 1 (by decide) ped.a ped.b (S_observable z) *
    Complex.ofReal ((Laguerre.polynomial (recenteredGammaShape n) ped.m).eval (R_poly z))

/-- Every member belongs to the actual three-generator polynomial algebra. -/
theorem polynomialEigenfunction_isPolynomial (n : ℕ) (ped : PolynomialEigenfunctionData n) :
    IsPolynomialInSConjSR (polynomialEigenfunction n ped) := by
  let H := MvPolynomial.rename Fin.castSucc
    (ComplexHermite.normalized 1 (by decide) ped.a ped.b)
  let L : MvPolynomial (Fin 3) ℂ :=
    (Laguerre.polynomial (recenteredGammaShape n) ped.m).eval₂
      (MvPolynomial.C.comp Complex.ofRealHom) (MvPolynomial.X 2)
  refine ⟨H * L, ?_⟩
  intro z
  let v : Fin 3 → ℂ := ![S_observable z, conj (S_observable z), (R_poly z : ℂ)]
  have hv : v ∘ Fin.castSucc = ![S_observable z, conj (S_observable z)] := by
    funext i
    fin_cases i <;> rfl
  have hH : MvPolynomial.eval v H =
      ComplexHermite.normalizedEval 1 (by decide) ped.a ped.b (S_observable z) := by
    simp only [H, MvPolynomial.eval_rename, hv, ComplexHermite.normalizedEval]
  have hL : MvPolynomial.eval v L =
      Complex.ofReal ((Laguerre.polynomial (recenteredGammaShape n) ped.m).eval (R_poly z)) := by
    change (MvPolynomial.eval₂Hom (RingHom.id ℂ) v) _ = _
    rw [Polynomial.hom_eval₂]
    have hc : (MvPolynomial.eval₂Hom (RingHom.id ℂ) v).comp
        (MvPolynomial.C.comp Complex.ofRealHom) = Complex.ofRealHom := by
      ext x; simp
    rw [hc]
    simpa [v] using (Polynomial.eval₂_hom
      (p := Laguerre.polynomial (recenteredGammaShape n) ped.m) Complex.ofRealHom (R_poly z))
  change _ = MvPolynomial.eval v (H * L)
  rw [map_mul, hH, hL]
  rfl

/-- The Hermite–Laguerre family is symmetric under particle permutations. -/
theorem polynomialEigenfunction_permute (n : ℕ) (ped : PolynomialEigenfunctionData n)
    (σ : ParticlePermutation n) (z : Configuration n) :
    polynomialEigenfunction n ped (permute σ z) = polynomialEigenfunction n ped z := by
  simp [polynomialEigenfunction, S_observable, R_poly, coordinateSum_permute,
    pairwiseRadius_permute]

/-- The radial Laguerre equation, evaluated at the concrete pair-distance radius. -/
theorem radial_laguerre_equation (n m : ℕ) (hn : 2 ≤ n) (z : Configuration n) :
    R_poly z * (Laguerre.polynomial (recenteredGammaShape n) m).derivative.derivative.eval (R_poly z) +
      ((recenteredGammaShape n : ℝ) - R_poly z) *
        (Laguerre.polynomial (recenteredGammaShape n) m).derivative.eval (R_poly z) =
      -(m : ℝ) * (Laguerre.polynomial (recenteredGammaShape n) m).eval (R_poly z) :=
  Laguerre.differential_equation _ _ (recenteredGammaShape_pos n hn) _

/-- The constant member of the family. -/
def P_000 {n : ℕ} (_z : Configuration n) : ℂ := 1
/-- The first holomorphic sum coordinate. -/
def P_100 {n : ℕ} (z : Configuration n) : ℂ := S_observable z
/-- The first antiholomorphic sum coordinate. -/
def P_010 {n : ℕ} (z : Configuration n) : ℂ := conj (S_observable z)
/-- The first radial polynomial. -/
def P_001 {n : ℕ} (z : Configuration n) : ℂ := (recenteredGammaShape n : ℂ) - R_poly z
/-- The second holomorphic sum polynomial. -/
def P_200 {n : ℕ} (z : Configuration n) : ℂ := (S_observable z)^2 / Real.sqrt 2
/-- The mixed sum polynomial. -/
def P_110 {n : ℕ} (z : Configuration n) : ℂ := Complex.normSq (S_observable z) - 1
/-- The second antiholomorphic sum polynomial. -/
def P_020 {n : ℕ} (z : Configuration n) : ℂ := (conj (S_observable z))^2 / Real.sqrt 2

@[simp] theorem polynomialEigenfunction_zero (n : ℕ) (z : Configuration n) :
    polynomialEigenfunction n ⟨0, 0, 0⟩ z = P_000 z := by
  simp [polynomialEigenfunction, P_000]

@[simp] theorem polynomialEigenfunction_first_radial (n : ℕ) (z : Configuration n) :
    polynomialEigenfunction n ⟨0, 0, 1⟩ z = P_001 z := by
  simp [polynomialEigenfunction, P_001, Laguerre.polynomial_one]

@[simp] theorem polynomialEigenfunction_first_holomorphic (n : ℕ) (z : Configuration n) :
    polynomialEigenfunction n ⟨1, 0, 0⟩ z = P_100 z := by
  simp [polynomialEigenfunction, P_100, ComplexHermite.oneDimNormalization]

@[simp] theorem polynomialEigenfunction_first_antiholomorphic (n : ℕ) (z : Configuration n) :
    polynomialEigenfunction n ⟨0, 1, 0⟩ z = P_010 z := by
  simp [polynomialEigenfunction, P_010, ComplexHermite.oneDimNormalization]

/-- The constant Hermite–Laguerre member satisfies the concrete generator equation. -/
theorem polynomialEigenfunction_zero_generator (n : ℕ) (z : Configuration n) :
    complexGinibrePregenerator n (polynomialEigenfunction n ⟨0, 0, 0⟩) z = 0 := by
  have heq : polynomialEigenfunction n ⟨0, 0, 0⟩ = fun _ => (1 : ℂ) := by
    funext w; simp [P_000]
  simp [complexGinibrePregenerator, P_000]

/-- The first holomorphic Hermite–Laguerre member satisfies the concrete eigenvalue equation. -/
theorem polynomialEigenfunction_first_holomorphic_generator (n : ℕ) (z : Configuration n) :
    complexGinibrePregenerator n (polynomialEigenfunction n ⟨1, 0, 0⟩) z =
      -(eigenvalue n 1 0 0 : ℂ) * polynomialEigenfunction n ⟨1, 0, 0⟩ z := by
  have heq : polynomialEigenfunction n ⟨1, 0, 0⟩ = coordinateSum := by
    funext w; simp [P_100, S_observable]
  rw [heq, complexGinibrePregenerator_coordinateSum]
  norm_num [eigenvalue]

end
end GinibrePoincare
